name: C++ Build

on:
  push:
  pull_request:

jobs:
  build:
    name: C++ Build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2026-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x spotlessApply
